### ISSUE TITLE
how did you get the enigne to be able to port?

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [APRO716/FNF-Hilo-Engine#1]
### What is your question?

How did you port the psychengine for me it wont work

**Comment by APRO716** [comment]
This is Based on Psych Engine

**Comment by hilonothiro** [comment]
thank for the question!!!
I am the creater of fnf hiro mod
this engine is modified from psych engine already
(too much modified)
if you have a problem you can tell me :)

**Comment by APRO716** [comment]
> this engine is modified from psych engine already

Yeah He is The Creator on Hilo Engine

**Comment by APRO716** [comment]
Thank You for Interesting our Hilo Engine :D I will close Issue now Bye :D
